pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'waterteleport'

def registerVersion(String name, String dir) {
	include name
	project(":${name}").projectDir = file("versions/${dir}")
}

registerVersion('waterteleport-1.20.1', '1.20.1')
registerVersion('waterteleport-1.20.4', '1.20.4')
registerVersion('waterteleport-1.21.1', '1.21.1')
registerVersion('waterteleport-1.21.4', '1.21.4')
registerVersion('waterteleport-1.21.11', '1.21.11')
registerVersion('waterteleport-26.1.2', '26.1.2')
registerVersion('waterteleport-26.2', '26.2')
