plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

version = "${rootProject.mod_version}+mc${project.minecraft_version}"
group = rootProject.maven_group
base.archivesName = rootProject.archives_base_name

loom {
	splitEnvironmentSourceSets()

	mods {
		"waterteleport" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets {
	main {
		java {
			srcDirs = [
				rootProject.file("src/${project.era_dir}/java"),
				rootProject.file("src/common/main/java")
			]
		}
		resources {
			srcDirs = [rootProject.file("src/main/resources")]
		}
	}
	client {
		java {
			srcDirs = [rootProject.file("src/${project.era_dir}/client/java")]
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", rootProject.mod_version
	inputs.property "minecraft_dependency", project.minecraft_dependency
	inputs.property "java_dependency", project.java_dependency

	filesMatching("fabric.mod.json") {
		expand "version": rootProject.mod_version,
		       "minecraft_dependency": project.minecraft_dependency,
		       "java_dependency": project.java_dependency
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
	it.options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	from(rootProject.file("LICENSE")) {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}
